config/routes.rb
Rails.application.routes.draw do
  root to: 'home#welcome' 
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
        @tasks = Task.all
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def new
    end

    def create
      @task = Task.new(description: params[:task][:description],
    status: params[:task][:status])
      @task.save
      redirect_to root_path
    end    
    
    def edit
       @task = Task.find(params[:id])
    end    

    def update
      @task = Task.find(params[:id])
      @task.update(params.require(:task).permit(:description, :status))
      redirect_to root_path
    end    

    def destroy
        task = Task.find(params[:id])
        task.destroy
        redirect_to root_path
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/welcome.html.erb
<h1>Bem-vindo ao Task List!</h1>
<h3>Sua lista de tarefas:</h3>

<% @tasks.each do |task| %>
  <ul>
    <li>
    <%= task.description %>
    <%= link_to 'Editar', edit_task_path(task) %>
    <%= link_to 'Apagar', task_path(task), method: :delete,
        data: { confirm: 'Quer apagar esta tarefa?' } %>
    </li>    
   </ul>     
<% end %>

<%= link_to 'Criar nova tarefa', new_task_url() %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
<%= f.label :description, 'Descrição' %>
<%= f.text_field :description %>
<%= f.label :status, 'Status' %>
<%= f.check_box :status %>
<%= f.submit 'Editar' %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for Task.new do |f| %>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_field :description %>
    <%= f.label :status, 'Status' %>
    <%= f.check_box :status %>
    <%= f.submit 'Criar' %>
<% end %>